version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bust_postgres
    environment:
      POSTGRES_DB: bust_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bust_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  bust_pg_data:
